-- Add Software Design category and assign tags
-- This migration creates a new category and assigns all the specified tags

-- 1. Create the Software Design category
INSERT INTO categories (name, description)
VALUES ('Software Design', 'UI/UX patterns, components, and design elements for software interfaces')
ON CONFLICT (name) DO NOTHING;

-- 2. Get the category ID and assign tags
WITH software_design_category AS (
  SELECT id FROM categories WHERE name = 'Software Design'
),
tag_list AS (
  SELECT unnest(ARRAY[
    'stack',
    'settings',
    'divider',
    'profile',
    'drop shadow',
    'container',
    'dropzone',
    'timer',
    'folder',
    'icon',
    'selection',
    'bottom sheet',
    'drawer',
    'paging',
    'record',
    'audio',
    'expand',
    'collapse',
    'interaction',
    'navigation',
    'number pad',
    'numpad',
    'video',
    'pull',
    'menu',
    'carousel',
    'surface',
    'transition',
    'edit',
    'dialog',
    'reveal more',
    'segmented control',
    'button',
    'voice recording',
    'swipe',
    'toggle',
    'confirmation',
    'header',
    'feedback',
    'chat',
    'touch',
    'drag n drop',
    'modality change',
    'day',
    'time',
    'skillset',
    'picker',
    'page transition',
    'map',
    'canvas',
    'operating system',
    'tabs',
    'checklist',
    'recording',
    'progress',
    'tags',
    'chips',
    'node based',
    'lists',
    'zoom',
    'block based interface',
    'visual divider',
    'addition',
    'search box',
    'image gallery',
    'timeline',
    'etch n scratch',
    'text input',
    'date picker',
    'icons in product',
    'radio button',
    'ui animation',
    'video player',
    'notification',
    'image loading',
    'typing',
    'links',
    'drawers',
    'file download',
    'hover',
    'network',
    'paint to reveal',
    'porfolio',
    'dock',
    'top menu',
    'image reveal',
    'flipping',
    'focus state',
    'bento',
    'spaces',
    'account change',
    'hovering',
    'location',
    'filters',
    'streak',
    'images',
    'calculation',
    'task',
    'overlay',
    'action sheet',
    'micro-interaction',
    'form active state',
    'details',
    'loading',
    'quotation',
    'reference',
    'app icon',
    'custom type interface',
    'signature',
    'weather',
    'gated',
    'slide up',
    'listening',
    'voice ui',
    'micro-animation',
    'counter animation',
    'kareoke',
    'lyrics',
    'bookmark',
    'screenshot',
    'dynamic island',
    'transfer',
    'share',
    'scroll',
    'image search'
  ]) AS tag_name
)
-- 3. Assign tags to the Software Design category
INSERT INTO category_tags (category_id, tag_id)
SELECT sdc.id, t.id
FROM software_design_category sdc
CROSS JOIN tag_list tl
JOIN tags t ON LOWER(t.name) = LOWER(tl.tag_name)
ON CONFLICT (category_id, tag_id) DO NOTHING; 